name: Package Development branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Setup NuGet Auth
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ontomortgage/IceSculptures/index.json"
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore ./TodDoModels.csproj
    - name: Build
      working-directory: ./src
      run: dotnet build ./TodDoModels.csproj --no-restore
    - name: Package
      working-directory: ./src
      run: dotnet pack ./TodDoModels.csproj --no-build --verbosity normal
    - name: Push to Git Nuget
      working-directory: ./src/bin/Release
      run: dotnet nuget push ./TodDoModels*.nupkg --username USERNAME --password${{ secrets.GITHUB_TOKEN }} --source "github"  
