name: Package Development branch

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pack-models:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      working-directory: ./src
      run: dotnet restore ./ToDoModels.csproj
    - name: Build
      working-directory: ./src
      run: dotnet build -c Release ./ToDoModels.csproj --no-restore
    - name: Package
      working-directory: ./src
      run: dotnet pack ./ToDoModels.csproj -c Release --no-build --verbosity normal
    - name: Push to Git Nuget
      working-directory: ./src/bin/Release
      run: dotnet nuget push ./ToDoModels*.nupkg --api-key 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  --source "github"  
